### ISSUE TITLE
README incompleto

### ISSUE THREAD

**Issue by CarolANikolic** [lilian-rangel/Projeto-Quiz#1]
Oi Lilian, tudo bem?

Conforme o feedback enviado sobre o seu projeto no Discord, segue minha sugestão sobre o README:

A apresentação do seu projeto é muito importante para que quem visite o seu código saiba do que se trata, possa utilizar a aplicação e trabalhar com o seu código. Portanto, segue uma sugestão de estruturação do README: https://blog.rocketseat.com.br/como-fazer-um-bom-readme/

Obs.: Adicione também o link para a sua aplicação para que possamos acessar. Estou curiosa para fazer o seu quiz!

Se precisar de qualquer ajuda, conte comigo!

Abraço,

Carol

**Comment by lilian-rangel** [comment]
Oi Carol, muito obrigada pelo feedback.

Arrumei o readme e fiz o deploy do jogo.
Agora está disponível para testes no link: [https://lilian-rangel-projeto-quiz.netlify.app/](url)
